apiVersion: v1
kind: Service
metadata:
  name: bitwarden-cli
  namespace: external-secrets
spec:
  selector:
    app: bitwarden-cli
  ports:
  - protocol: TCP
    port: 8087
    targetPort: 8087
  type: ClusterIP
