---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-postgresql
  namespace: authentik
  labels:
    external-secrets.io/type: webhook
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: authentik-postgresql
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: password
      remoteRef:
        key: b7fa7c52-09bd-48e4-aa8c-c86ba9d0a9be
        property: password
    - secretKey: postgres-password
      remoteRef:
        key: b7fa7c52-09bd-48e4-aa8c-c86ba9d0a9be
        property: postgres-password
