apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: smtp-secret
  namespace: authentik
  labels:
    external-secrets.io/type: webhook
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: a1ba9084-f041-4da6-aa90-ae98428b7cbb
        property: username
    - secretKey: password
      remoteRef:
        key: a1ba9084-f041-4da6-aa90-ae98428b7cbb
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-secret
  namespace: authentik
  labels:
    external-secrets.io/type: webhook
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    creationPolicy: Owner
  data:
    - secretKey: secret-key
      remoteRef:
        key: c5151c6c-c825-40ef-a3b5-cec7f985b3d1
        property: username
    - secretKey: postgresql-password
      remoteRef:
        key: c5151c6c-c825-40ef-a3b5-cec7f985b3d1
        property: password
