---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-oauth-secret
  namespace: authentik
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        key: a5046bc6-61cb-477a-be6c-031c6c1126d4
        property: username
    - secretKey: client-secret
      remoteRef:
        key: a5046bc6-61cb-477a-be6c-031c6c1126d4
        property: password
