apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - blueprints-configmap.yaml
  - external-secret.yaml
  - externalsecret-postgres.yaml
  - github-oauth-secret.yaml
  - httproute.yaml
  - reference-grants.yaml
  - synology-nas.yaml
