global:
  env:
    - name: AUTHENTIK_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: authentik-secret
          key: secret-key
    - name: AUTHENTIK_POSTGRESQL__PASSWORD
      valueFrom:
        secretKeyRef:
          name: authentik-secret
          key: postgresql-password
    - name: AUTHENTIK_EMAIL__USERNAME
      valueFrom:
        secretKeyRef:
          name: smtp-secret
          key: username
    - name: AUTHENTIK_EMAIL__FROM
      valueFrom:
        secretKeyRef:
          name: smtp-secret
          key: username
    - name: AUTHENTIK_EMAIL__PASSWORD
      valueFrom:
        secretKeyRef:
          name: smtp-secret
          key: password

authentik:
    error_reporting:
        enabled: false
    email:
        host: smtp.gmail.com
        port: 587
        use_tls: true

server:
    replicas: 1
    ingress:
        enabled: false
    service:
        type: ClusterIP
    volumes:
        - name: blueprints
          configMap:
              name: authentik-blueprints
    volumeMounts:
        - name: blueprints
          mountPath: /blueprints/custom

worker:
    replicas: 1
    volumes:
        - name: blueprints
          configMap:
              name: authentik-blueprints
    volumeMounts:
        - name: blueprints
          mountPath: /blueprints/custom

postgresql:
    enabled: true
    auth:
        username: authentik
        database: authentik
        existingSecret: authentik-postgresql
    primary:
      persistence:
        enabled: true
        existingClaim: data-authentik-postgresql-0

redis:
    enabled: true
    master:
      persistence:
        enabled: true
        existingClaim: redis-data-authentik-redis-master-0
