defaults {
    user_friendly_names yes
}

blacklist {
    devnode "^(sd[a-z]|nvme)"
    device {
        vendor "IET"
        product "VIRTUAL-DISK"
    }
    device {
        vendor "SYNOLOGY"
        product "iSCSI Storage"
    }
}
