apiVersion: apps/v1
kind: Deployment
metadata:
  name: spotdl
  namespace: web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spotdl
  template:
    metadata:
      labels:
        app: spotdl
    spec:
      containers:
        - name: spotdl-container
          image: spotdl/spotify-downloader:latest
          args: ["download https://open.spotify.com/playlist/1QUPeQyWAz5hBdIYGIhahi?si=e23fbbbe1eef45d3"]
          ports:
            - containerPort: 8800
---
apiVersion: v1
kind: Service
metadata:
  name: spotdl-webserver
  namespace: web-server
spec:
  selector:
    app: spotdl
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8800
  type: LoadBalancer
