---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-oidc-secret
  namespace: argocd
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        key: argocd-oidc-authentik
        property: username
    - secretKey: client-secret
      remoteRef:
        key: argocd-oidc-authentik
        property: password
