---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: theswamp
  namespace: tooling
spec:
  interval: 5m
  path: ./rke2/tooling/flux/theswamp
  prune: true
  sourceRef:
    kind: GitRepository
    name: tooling
    namespace: tooling
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: image-automation
  namespace: tooling
spec:
  interval: 5m
  path: ./rke2/tooling/flux/image-automation
  prune: true
  sourceRef:
    kind: GitRepository
    name: tooling
    namespace: tooling
