apiVersion: v1
kind: Service
metadata:
  name: vault-warden
  namespace: external-secrets
spec:
  selector:
    app: vault-warden
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  clusterIP: 10.43.1.1
  type: ClusterIP
