---
apiVersion: cloudflare-operator.io/v1
kind: DNSRecord
metadata:
  name: satisfactory
  namespace: game-server
spec:
  name: satisfactory.hwcopeland.net
  type: CNAME
  content: hwcopeland.net
  proxied: false
  ttl: 1
  interval: 5m
