---
apiVersion: cloudflare-operator.io/v1
kind: DNSRecord
metadata:
  name: kai
  namespace: kai
spec:
  name: kai.hwcopeland.net
  type: CNAME
  content: hwcopeland.net
  proxied: true
  ttl: 1
  interval: 5m
