---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: khemeia-result-writer
  namespace: chem
spec:
  image: zot.hwcopeland.net/chem/khemeia-result-writer
  interval: 5m
  secretRef:
    name: zot-pull-secret
