---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: ddg
  namespace: chem
spec:
  image: zot.hwcopeland.net/chem/ddg
  interval: 5m
  secretRef:
    name: zot-pull-secret
