---
- name: Ensure /etc/rancher/rke2 directory exists
  file:
    path: /etc/rancher/rke2
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Copy RKE2 server config
  copy:
    src: config.yaml
    dest: /etc/rancher/rke2/config.yaml
    owner: root
    group: root
    mode: '0644'

- name: Install RKE2 server
  shell: curl -sfL https://get.rke2.io | sh -
  args:
    creates: /usr/local/bin/rke2

- name: Enable and start rke2-server service
  systemd:
    name: rke2-server
    enabled: true
    state: started

- name: Wait for Kubernetes API server to be ready
  command: /var/lib/rancher/rke2/bin/kubectl get nodes --kubeconfig /etc/rancher/rke2/rke2.yaml
  register: result
  retries: 30
  delay: 10
  until: result.rc == 0
  changed_when: false

- name: Create .kube directory for user
  file:
    path: "/home/{{ ansible_user }}/.kube"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Copy kubeconfig to user's home
  copy:
    src: /etc/rancher/rke2/rke2.yaml
    dest: "/home/{{ ansible_user }}/.kube/config"
    remote_src: true
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'
