apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - config/rbac.yaml
  - config/deployment.yaml
  - config/mysql.yaml
  - config/result-writer-deployment.yaml
  - zot-pull-secret.yaml
