apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - crd/dockingjob-crd.yaml
  - config/rbac.yaml
  - config/deployment.yaml
  - config/pvc-autodock.yaml
  - config/mysql.yaml
  - zot-pull-secret.yaml
