---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cs2-secret-external
  namespace: game-server
  labels:
    external-secrets.io/type: webhook
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: cs2-secret
    creationPolicy: Owner
  data:
    - secretKey: API_KEY
      remoteRef:
        key: cs2-server-config
        property: API_KEY
    - secretKey: STEAM_ACCOUNT
      remoteRef:
        key: cs2-server-config
        property: STEAM_ACCOUNT
