apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-storage
  namespace: game-server
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: synology-iscsi-storage
  resources:
    requests:
      storage: 1Ti
