apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cs2-rcon
  namespace: game-server
  labels:
    external-secrets.io/type: webhook
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: 01bbf2c8-1ac7-4906-9955-144ab2062ab8
        property: password
