apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - imagerepository-kai-api.yaml
  - imagerepository-kai-agent.yaml
  - imagepolicy-kai-api.yaml
  - imagepolicy-kai-agent.yaml
  - imageupdateautomation.yaml
