apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: atm9skies
  namespace: game-server
spec:
  replicas: 1
  serviceName: atm9skies-service
  selector:
    matchLabels:
      app: atm9skies
  template:
    metadata:
      labels:
        app: atm9skies
    spec:
      containers:
        - name: atm9skies-server
          image: itzg/minecraft-server:java21-alpine
          ports:
            - containerPort: 25565
          env:
            - name: EULA
              value: "true"
            - name: MODPACK_PLATFORM
              value: "AUTO_CURSEFORGE"
            - name: CF_API_KEY
              valueFrom:
                secretKeyRef:
                  name: curseforge-secret
                  key: CF_API_KEY
            - name: CF_SLUG
              value: "all-the-mods-9-to-the-sky"
            - name: CF_EXCLUDE_MODS
              value: "particle-effects-reforged"
            - name: MEMORY
              value: "10G"
          volumeMounts:
            - name: mc-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: mc-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: longhorn
        resources:
          requests:
            storage: 50Gi
---
apiVersion: v1
kind: Service
metadata:
  name: atm9skies-external
  namespace: game-server
  annotations:
    "mc-router.itzg.me/defaultServer": "true"
    "mc-router.itzg.me/externalServerName": "atm9skies.hwcopeland.net"
spec:
  type: ClusterIP
  selector:
    app: atm9skies
  ports:
    - protocol: TCP
      port: 25565
---
apiVersion: v1
kind: Service
metadata:
  name: atm9skies-local
  namespace: game-server
spec:
  type: LoadBalancer
  selector:
    app: atm9skies
  ports:
    - protocol: TCP
      port: 25565
      targetPort: 25565
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: serverless-watcher
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["watch", "list"]
  - apiGroups: ["apps"]
    resources: ["statefulsets", "statefulsets/scale"]
    verbs: ["watch", "list", "get", "update"]
