apiVersion: cloudflare-operator.io/v1
kind: DNSRecord
metadata:
  name: docking-controller
  namespace: chem
spec:
  name: docking-controller.hwcopeland.net
  content: hwcopeland.net
  type: CNAME
  ttl: 1
  proxied: true
  interval: 5m
