apiVersion: apps/v1
kind: Deployment
metadata:
  name: excalidraw
  namespace: web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: excalidraw
  template:
    metadata:
      labels:
        app: excalidraw
    spec:
      containers:
        - name: excalidraw-container
          image: excalidraw/excalidraw:latest # Using the official image
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: excalidraw-service
  namespace: web-server
spec:
  selector:
    app: excalidraw
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
