---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zot-oidc-secret
  namespace: tooling
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        credentials.json: |
          {
            "clientid": "{{ .client_id }}",
            "clientsecret": "{{ .client_secret }}"
          }
  data:
    - secretKey: client_id
      remoteRef:
        key: 3a60973d-5431-4004-9792-29b5374ce6e4
        property: username
    - secretKey: client_secret
      remoteRef:
        key: 3a60973d-5431-4004-9792-29b5374ce6e4
        property: password
