apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: wireguard-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.255.255.128-10.255.255.254
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: wireguard-adv
  namespace: metallb-system
spec:
  ipAddressPools:
  - wireguard-pool
---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: opnsense
  namespace: metallb-system
spec:
  myASN: 65552
  peerASN: 65551
  peerAddress: 10.255.255.1
  sourceAddress: 10.255.255.4
