apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: 44pool
  namespace: metallb-system
spec:
  addresses:
  - 10.44.0.1-10.44.0.254
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: external-advertisment
  namespace: metallb-system
spec:
  ipAddressPools:
  - 44pool
---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: mikrotik-ccr
  namespace: metallb-system
spec:
  myASN: 65551
  peerASN: 65551
  peerAddress: 10.0.0.1
  sourceAddress: 10.0.0.239
