apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-namespace.yaml
  - garage-secret-dev.yaml
  - garage-config.yaml
  - garage-pvcs.yaml
  - garage-statefulset.yaml
  - garage-service.yaml
  - garage-lifecycle-cronjob.yaml
