# apt packages
- name: Install Curl
  package:
    name: curl
    state: present

- name: Install iptables
  package:
    name: iptables
    state: present

- name: Install nfs-common
  package:
    name: nfs-common
    state: present
