---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: demo-mcp
  namespace: tooling
spec:
  image: zot.hwcopeland.net/florida-man-bioscience/demo-mcp
  interval: 1m0s
  secretRef:
    name: zot-pull-secret
