apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openclaw-secrets
  namespace: agent-system
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: openclaw-secrets
    creationPolicy: Owner
  data:
    - secretKey: OPENCLAW_GATEWAY_TOKEN
      remoteRef:
        key: bd39ca25-f598-4dfd-ad3b-837641242bbb
        property: password
    - secretKey: GROQ_API_KEY
      remoteRef:
        key: f4e26d00-1fde-4b60-8a31-a02f5e6f543b
        property: password
    - secretKey: GH_TOKEN
      remoteRef:
        key: f0e0f3c1-111a-445f-b352-d942257fa7be
        property: password
    - secretKey: GEMINI_API_KEY
      remoteRef:
        key: 59d77ce0-8322-4850-9ed4-aff3413822ca
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-secrets
  namespace: agent-system
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: oauth2-proxy-secrets
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        key: 3f9f5b2e-e28b-46f7-b232-3b5af84882c3
        property: username
    - secretKey: client-secret
      remoteRef:
        key: 3f9f5b2e-e28b-46f7-b232-3b5af84882c3
        property: password
    - secretKey: cookie-secret
      remoteRef:
        key: 049e12fd-061e-458e-95c3-0612324f92e4
        property: password
