---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cf-flmanbiosci-wildcard-cert
  namespace: kube-system
spec:
  dnsNames:
    - "*.flmanbiosci.net"
    - flmanbiosci.net
  issuerRef:
    kind: ClusterIssuer
    name: cf-issuer
  secretName: cf-flmanbiosci-wildcard-cert-secret
