---
apiVersion: cloudflare-operator.io/v1
kind: DNSRecord
metadata:
  name: flmanbiosci-root
  namespace: kube-system
spec:
  name: flmanbiosci.net
  type: A
  content: 69.180.240.158
  proxied: true
  ttl: 1
  interval: 5m
