---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cs2-volume-claim
  namespace: game-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi   # Adjust size as needed
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cs2-modded-server
  namespace: game-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cs2-modded-server
  template:
    metadata:
      labels:
        app: cs2-modded-server
    spec:
      containers:
        - name: cs2-modded-server
          image: cs2-modded-server
          ports:
            - containerPort: 27015
              protocol: TCP
            - containerPort: 27015
              protocol: UDP
            - containerPort: 27020
              protocol: TCP
            - containerPort: 27020
              protocol: UDP
          # Import env vars from a ConfigMap (create one named "cs2-env" with your .env content)
          envFrom:
            - configMapRef:
                name: cs2-env
          resources:
            limits:
              memory: "3500Mi"
              cpu: "2"
          volumeMounts:
            - name: cs2-volume
              mountPath: /home/steam/
            - name: custom-files
              mountPath: /home/custom_files/
            - name: game
              mountPath: /home/game/
      volumes:
        - name: cs2-volume
          persistentVolumeClaim:
            claimName: cs2-volume-claim
        - name: custom
          hostPath:
            path: /home/k8s_user/iac/rke2/game-server/cs2/custom   # Change to your actual path
            type: Directory
        - name: game
          hostPath:
            path: /absolute/path/to/game           # Change to your actual path
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: cs2-modded-server-service
  namespace: game-server
spec:
  selector:
    app: cs2-modded-server
  ports:
    - name: tcp-27015
      protocol: TCP
      port: 27015
      targetPort: 27015
    - name: udp-27015
      protocol: UDP
      port: 27015
      targetPort: 27015
    - name: tcp-27020
      protocol: TCP
      port: 27020
      targetPort: 27020
    - name: udp-27020
      protocol: UDP
      port: 27020
      targetPort: 27020
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cs2-env
data:
  API_KEY: ''
  Port: 27015
  TICKRATE: 128
  MAXPLAYERS: 10
  STREAM_ACCOUNT: ''
  RCON_PASSWORD: 'password'
  CUSTOM_FOLDER: 'custom'
  EXEC: 'on_boot_cfg'
