apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: klipper-data
  namespace: iot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: klipper-gcode
  namespace: iot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
