---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hubble-oidc-secret
  namespace: kube-system
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: hubble-authentik-token
        property: password
