---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: n8n-oidc-secret
  namespace: agent-system
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        key: n8n-oidc-authentik
        property: username
    - secretKey: client-secret
      remoteRef:
        key: n8n-oidc-authentik
        property: password
