---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-dev
  namespace: web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextjs-dev
  template:
    metadata:
      labels:
        app: nextjs-dev
    spec:
      containers:
        - name: nextjs
          image: nextjs-app:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
  namespace: web-server
spec:
  selector:
    app: nextjs-dev
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
  loadBalancerClass: tailscale
