apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - external-secrets.yaml
  - dnsrecords.yaml
  - httproutes.yaml
patches:
  - path: patch-token-manager.yaml
    target:
      kind: Deployment
      name: openhands
      namespace: openhands
  - path: patch-runtime-api.yaml
    target:
      kind: Deployment
      name: openhands-runtime-api
      namespace: openhands
