bitbucket:
  enabled: false
env:
  AUTH_URL: https://aiauth.hwcopeland.net
  ENABLE_ENTERPRISE_SSO: "1"
  HIDE_LLM_SETTINGS: "true"
  KEYCLOAK_EXTERNAL_URL: https://aiauth.hwcopeland.net
  KEYCLOAK_SERVER_URL_EXT: https://aiauth.hwcopeland.net
  LITE_LLM_API_URL: http://openhands-litellm:4000
  LITELLM_DEFAULT_MODEL: litellm_proxy/prod/grok-4-reasoning
  RUNTIME_URL_PATTERN: http://runtime-{runtime_id}.openhands.svc.cluster.local:60000
filestore:
  ephemeral: true
github:
  enabled: false
gitlab:
  enabled: false
ingress:
  enabled: false
  host: ai.hwcopeland.net
keycloak:
  auth:
    adminPassword: ""
    existingSecret: keycloak-admin
    passwordSecretKey: admin-password
  enabled: true
  ingress:
    enabled: false
    hostname: aiauth.hwcopeland.net
  postgresql:
    auth:
      existingSecret: postgres-password
      secretKeys:
        adminPasswordKey: postgres-password
        userPasswordKey: password
  url: http://keycloak
litellm:
  enabled: true
  url: http://openhands-litellm:4000
litellm-helm:
  enabled: true
  envSecrets:
  - litellm-env-secrets
  ingress:
    enabled: false
  proxy_config:
    environment_variables:
      OR_APP_NAME: OpenHands
      OR_SITE_URL: https://docs.all-hands.dev
    model_list:
    - litellm_params:
        api_key: os.environ/XAI_API_KEY
        model: xai/grok-4.20-0309-reasoning
      model_name: prod/grok-4-reasoning
postgresql:
  auth:
    existingSecret: postgres-password
    secretKeys:
      adminPasswordKey: postgres-password
      userPasswordKey: password
  enabled: true
redis:
  auth:
    existingSecret: redis
    existingSecretPasswordKey: redis-password
  enabled: true
runtime-api:
  enabled: true
  env:
    RUNTIME_BASE_URL: ai-runtimes.hwcopeland.net
    STORAGE_CLASS: longhorn
  ingress:
    enabled: false
    host: ai-runtimes.hwcopeland.net
sandbox:
  apiHostname: https://ai-runtimes.hwcopeland.net
tls:
  enabled: false
