apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin-secret
  namespace: monitor
  labels:
    external-secrets.io/type: webhook
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: f808fa58-6297-4693-be81-a80c964673e3
        property: username
    - secretKey: password
      remoteRef:
        key: f808fa58-6297-4693-be81-a80c964673e3
        property: password
