---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-oidc-secret
  namespace: monitor
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        key: dd0f88cc-82a7-415c-b7de-660f3d492025
        property: username
    - secretKey: client-secret
      remoteRef:
        key: dd0f88cc-82a7-415c-b7de-660f3d492025
        property: password
