apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-grafana
  namespace: monitor
  annotations:
    cert-manager.io/cluster-issuer: "cf-issuer"
    cloudflare-operator.io/type: CNAME
    cloudflare-operator.io/content: hwcopeland.net
spec:
  ingressClassName: nginx
  rules:
    - host: grafana.hwcopeland.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kube-prometheus-stack-grafana
                port:
                  number: 3000
  tls:
    - hosts:
        - "*.hwcopeland.net"
      secretName: cf-wildcard-cert-secret

