apiVersion: v1
kind: Service
metadata:
  name: cs2-mysql
  namespace: game-server
spec:
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: cs2-mysql
  type: LoadBalancer
  loadBalancerIP: 10.44.44.44
  clusterIP: 10.43.43.43
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cs2-mysql-config
  namespace: game-server
data:
  custom.cnf: |
    [mysqld]
    port = 3306
    bind-address = 0.0.0.0
    skip-networking = OFF
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cs2-mysql
  namespace: game-server
spec:
  selector:
    matchLabels:
      app: cs2-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cs2-mysql
    spec:
      containers:
      - image: mysql:9
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        ports:
        - containerPort: 3306
          name: mysql
          protocol: TCP
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: mysql-config-volume
          mountPath: /etc/mysql/conf.d/custom.cnf
          subPath: custom.cnf

        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        # Add liveness probe to restart container if MySQL becomes unresponsive
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-cs2-pvc
      - name: mysql-config-volume
        configMap:
          name: cs2-mysql-config
