apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-secret
  namespace: game-server
  labels:
    external-secrets.io/type: webhook
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: 7abbd02a-44b1-45b6-8be6-114bfb0c9e82
        property: username
    - secretKey: password
      remoteRef:
        key: 7abbd02a-44b1-45b6-8be6-114bfb0c9e82
        property: password
