apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-media
  namespace: plex-system
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: synology-iscsi-plex
  resources:
    requests:
      storage: 25Ti  # Adjusted for media library size
