apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-iscsi-plex
provisioner: csi.san.synology.com
parameters:
  dsm: '10.41.0.200'
  location: '/volume1'
  fsType: 'xfs'
  formatOptions: '-f -K'
reclaimPolicy: Retain
allowVolumeExpansion: true
