apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rbac.yaml
  - plugins-configmap.yaml
  - api-deployment.yaml
  - web-deployment.yaml
  - result-writer.yaml
  - prolif-runner.yaml
  - mysql.yaml
  - mysql-secret.yaml
  - httproute.yaml
  - flux-webhook-secret.yaml
  - flux-webhook-receiver.yaml
