apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - crds/
  - rbac.yaml
  - rbac-crds.yaml
  - compute-classes.yaml
  - vina-gpu-kernel-cache-pvc.yaml
  - plugins-configmap.yaml
  - api-deployment.yaml
  - web-deployment.yaml
  - result-writer.yaml
  - prolif-runner.yaml
  - library-prep.yaml
  - admet.yaml
  - mysql.yaml
  - mysql-secret.yaml
  - httproute.yaml
  - flux-webhook-secret.yaml
  - flux-webhook-receiver.yaml
  - infra/
