apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: synology-csi-credentials
  namespace: kube-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: synology-csi-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: "84573c0a-616a-458a-8601-71d78809839e"
        property: username
    - secretKey: password
      remoteRef:
        key: "84573c0a-616a-458a-8601-71d78809839e"
        property: password
