apiVersion: v1
data:
  AWS_ACCESS_KEY_ID: MDA1Y2JhYzFjODAyMTNhMDAwMDAwMDAwMQ==
  AWS_ENDPOINTS: aHR0cHM6Ly9zMy51cy1lYXN0LTAwNS5iYWNrYmxhemViMi5jb20=
  AWS_SECRET_ACCESS_KEY: SzAwNXkvckJKUkdYUzRsVEViSWlYajBid0pFMVBTZw==
kind: Secret
metadata:
  annotations:
    longhorn.io/backup-target: s3://longhorn-hwcoplenad@s3.us-east-005.backblazeb2.com/
  creationTimestamp: "2026-01-13T19:04:45Z"
  name: b2-backup-secret
  namespace: longhorn-system
  resourceVersion: "155001563"
  uid: 0fc8e580-1592-494c-9123-16de054b4f14
type: Opaque
