---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: bitwarden-fields
spec:
  provider:
    webhook:
      headers:
        Content-Type: application/json
      result:
        jsonPath: "$.data.fields[?@.name=={{ .remoteRef.property | quote }}].value"
      url: http://bitwarden-cli:8087/object/item/{{ .remoteRef.key }}
