name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: DOCKER_HUB
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Check out repository
        uses: actions/checkout@v3
      -
        name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: ./rke2/web-server/info.hwcopeland.net
          file: ./rke2/web-server/info.hwcopeland.net/Dockerfile
          push: true
          tags: hwcopeland/web:latest
      -
        name: Update Image Tag Values
        run: |
          manifest_dir="./rke2/web-server/info.hwcopeland.net/k8s"
          new_image_tag=${{ github.sha }}

          sed -i "s/^ tag: .*/ tag: $new_image_tag/" "$manifest_dir/web-deployment.yaml"
      -
        name: Commit Changes
        run: |
          git config --global user.name 'hwcopeland'
          git config --global user.email 'hwc2e@mtmail.mtsu.edu'
          git commit -am "updating image tag"
          git push
