name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: DOCKER_HUB
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Check out repository
        uses: actions/checkout@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./rke2/web-server/info.hwcopeland.net/
          file: Dockerfile
          push: true
          tags: hwcopeland/web:latest
